### ISSUE TITLE
Normalize readme files: 1) English, 2) German

### ISSUE THREAD

**Issue by glueckpress** [pluginkollektiv/cachify#1]
Readme.md and readme.txt files should be normalized in the way that they should start with English and then provide a German translation (if already available) below.

This can obviously be contributed by the support team.

**Comment by swissspidy** [comment]
Note: The Amazon link in the readme doesn't work anymore.

**Comment by glueckpress** [comment]
Added English translation, first draft. (Temporarily removed German content.) This is what the description page should look like in the browser:

![58da57cd-5818-4f25-a7bd-c3891b0cd9fe](https://cloud.githubusercontent.com/assets/308422/8656003/325d73fc-2995-11e5-974c-fb150817c72d.png)
