### ISSUE TITLE
Cachify create html file, but doesnt deliver it

### ISSUE THREAD

**Issue by petrk94** [pluginkollektiv/cachify#101]
Hello,
I have read about the Cachify and like it, but I have an issue what Im not sure how to solve, when Im reloading the site again, I dont see a change in the requests nor change in the file sizes.
In Filezilla I could find the folder for cachify cache, even the html / gz file got created + sub folders of the pages, but it doesnt deliver the html file to browser.
Is there something else I need to setup?

Im using this tutorial https://github.com/pluginkollektiv/cachify/wiki/en-Cache-Methods#hard-disk-hdd-cache and have HDD cache activated.

Thanks

**Comment by Zodiac1978** [comment]
Github issues are for bug reports and not for support. Please use the support forums next time. Thank you! :)

If you look at your source code in the browser, is there something like that at the end:
``

If not, please post your htaccess code or nginx code, so that we can check it.

**Comment by petrk94** [comment]
Ah alright, I will send asap I have access. Was not sure whether it is a bug or a feature I can not find ;)

**Comment by petrk94** [comment]
@Zodiac1978 
Hello I had finally the chance to get the .htaccess code.
I have looked in the source code of the website, but I could not find the string (similar) what you have noticed before. But I could see that Cachify is activated in the script parts below footer.

Here is the .htaccess code:

```
# BEGINN CACHIFY
# Code from https://github.com/pluginkollektiv/cachify/wiki/en-Cache-Methods#hard-disk-hdd-cache
<IfModule mod_rewrite.c>
    # ENGINE ON
    RewriteEngine On

    # GZIP FILE
    <IfModule mod_mime.c>
        RewriteCond %{REQUEST_URI} /$
        RewriteCond %{REQUEST_URI} !^/(wp-admin|wp-content/cache)/.*
        RewriteCond %{REQUEST_METHOD} !=POST
        RewriteCond %{QUERY_STRING} =""
        RewriteCond %{HTTP_COOKIE} !(wp-postpass|wordpress_logged_in|comment_author)_
        RewriteCond %{HTTP:Accept-Encoding} gzip
        RewriteCond %{DOCUMENT_ROOT}wp-content/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html.gz -f
        RewriteRule ^(.*) wp-content/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html.gz [L]

        AddType text/html .gz
        AddEncoding gzip .gz
    </IfModule>

    # HTML FILE
    RewriteCond %{REQUEST_URI} /$
    RewriteCond %{REQUEST_URI} !^/(wp-admin|wp-content/cache)/.*
    RewriteCond %{REQUEST_METHOD} !=POST
    RewriteCond %{QUERY_STRING} =""
    RewriteCond %{HTTP_COOKIE} !(wp-postpass|wordpress_logged_in|comment_author)_
    RewriteCond %{DOCUMENT_ROOT}wp-content/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html -f
    RewriteRule ^(.*) /wp-content/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html [L]
</IfModule>
# END CACHIFY



# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress


# Change after 28.05.17

# Enable expirations
ExpiresActive On
# Default directive
ExpiresDefault "access plus 1 month"
# My favicon
ExpiresByType image/x-icon "access plus 1 year"
# Images
ExpiresByType image/gif "access plus 1 month"
ExpiresByType image/png "access plus 1 month"
ExpiresByType image/jpg "access plus 1 month"
ExpiresByType image/jpeg "access plus 1 month"
# CSS
ExpiresByType text/css "access plus 1 month"
# Javascript
ExpiresByType application/javascript "access plus 1 year"



# Compress HTML, CSS, JavaScript, Text, XML and fonts
AddOutputFilterByType DEFLATE application/javascript
AddOutputFilterByType DEFLATE application/rss+xml
AddOutputFilterByType DEFLATE application/vnd.ms-fontobject
AddOutputFilterByType DEFLATE application/x-font
AddOutputFilterByType DEFLATE application/x-font-opentype
AddOutputFilterByType DEFLATE application/x-font-otf
AddOutputFilterByType DEFLATE application/x-font-truetype
AddOutputFilterByType DEFLATE application/x-font-ttf
AddOutputFilterByType DEFLATE application/x-javascript
AddOutputFilterByType DEFLATE application/xhtml+xml
AddOutputFilterByType DEFLATE application/xml
AddOutputFilterByType DEFLATE font/opentype
AddOutputFilterByType DEFLATE font/otf
AddOutputFilterByType DEFLATE font/ttf
AddOutputFilterByType DEFLATE image/svg+xml
AddOutputFilterByType DEFLATE image/x-icon
AddOutputFilterByType DEFLATE text/css
AddOutputFilterByType DEFLATE text/html
AddOutputFilterByType DEFLATE text/javascript
AddOutputFilterByType DEFLATE text/plain
AddOutputFilterByType DEFLATE text/xml


```

**Comment by Zodiac1978** [comment]
> but I could not find the string (similar) what you have noticed before

Okay, so the htaccess code is *not* working.

The crucial part is the path. 
`        RewriteCond %{DOCUMENT_ROOT}wp-content/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html.gz -f
        RewriteRule ^(.*) wp-content/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html.gz [L]`

and 

`    RewriteCond %{DOCUMENT_ROOT}wp-content/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html -f
    RewriteRule ^(.*) /wp-content/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html [L]`

You can check with this PHP line if the path is correct:
https://gist.github.com/sergejmueller/5501098

The path should be starting with a leading "/" - this is just right in the last case.

With the correct path and a leading slash it should work and you should see the mention of Cachify in the source code.

**Comment by Zodiac1978** [comment]
Maybe your host is not providing the variable %{DOCUMENT_ROOT} correctly. With the mentioned gist you can find the correct path and use this.

**Comment by Zodiac1978** [comment]
Closed due to missing feedback
