### ISSUE TITLE
Cachify does not inform user that cache has been cleared when flushing cache from frontend

### ISSUE THREAD

**Issue by chesio** [pluginkollektiv/cachify#102]
When user clicks on Cachify flush button in admin bar when viewing front-end page, cache is cleared and page reloads, but there is no indication of success or error, so to the user it seems as nothing has happened.

Possible solutions (sorted by implementation complexity):
1. Do not show flush button in admin bar, when viewing non-admin page.
1. Redirect to Dashboard page in admin and show a notice there using admin notices mechanism like it is currently done for admin pages.
1. AJAX-ify cache flushing action and show any notice within the current page.

The AJAX-based solution would be the best in my opinion. Cache flushing in [Autoptimize](https://github.com/futtta/autoptimize/) plugin works this way and it seems more UX friendly to me. Also, it would inherently fix #100.

**Comment by krafit** [comment]
I really like the AJAX solution too. What do you think, @bueltge, @websupporter?

**Comment by chesio** [comment]
Question: do you want to support IE9 users? I have an implementation of AJAX-ified cache flushing ready, but it uses [CSS Animations](http://caniuse.com/#feat=css-animation) to rotate a spinner that indicates that flushing is in progress (I got inspired by cache flushing indicator from TYPO3).

I'm currently testing this feature on one of my sites, but I like it already: cache flushing without page reload is way faster.

**Comment by websupporter** [comment]
> What do you think, [...], @websupporter?
sorry, totally missed that. Sounds good 😄

**Comment by angcl** [comment]
#257 This pull request may be the answer. It's a version that registers an REST API endpoint which is used to clear the cache.
