### ISSUE TITLE
Do not wp_die() in case of cache I/O error

### ISSUE THREAD

**Issue by chesio** [pluginkollektiv/cachify#106]
Hi,

I noticed that in case of I/O error, Cachify will terminate script execution via [wp_die()](https://developer.wordpress.org/reference/functions/wp_die/) (for example when [HDD cache dir cannot be created](https://github.com/pluginkollektiv/cachify/blob/master/inc/cachify_hdd.class.php#L159)).

I think a more sane approach is to [trigger an error](http://php.net/manual/en/function.trigger-error.php) instead, so error message gets silenced, logged or displayed (depending on [WP_DEBUG setting](https://codex.wordpress.org/Debugging_in_WordPress)), but requested page still loads normally. Website visitors should not be seeing 500 Internal server errors only because cache directory is not writable...

**Comment by krafit** [comment]
> Website visitors should not be seeing 500 Internal server errors only because cache directory is not writable...
Yep, this is terrible UX. I'd love to address this in v.2.4

**Comment by websupporter** [comment]
Should we also reconsider `wp_die()` in the `store_item()`, `get_item()` and `delete_item()` methods?

**Comment by chesio** [comment]
> Should we also reconsider wp_die() in the store_item(), get_item() and delete_item() methods?

I'd say so. I had a look and some of the instances can be completely removed in my opinion. For example, I think it is safe to assume that `$hash` is never empty:
```php
if ( empty( $hash ) ) {
	wp_die( 'APC delete item: Empty input.' );
}
```
