### ISSUE TITLE
Add composer.json file to the plugin

### ISSUE THREAD

**Issue by chesio** [pluginkollektiv/cachify#111]
Hi,

Having `composer.json` file in GitHub repo would make it easier to fetch updates from master branch via Composer. I'm currently running master branch in several of my projects, because Cachify version in WordPress Plugin Directory (and thus [WordPress Packagist](https://wpackagist.org/) as well) is a bit outdated in the moment...

**Comment by krafit** [comment]
The version in the .org directory is the current stable version, as far as I'm concerned. So fetching updates from there seems about right. A composer.json might be an option for the future though.

**Comment by chesio** [comment]
> The version in the .org directory is the current stable version, as far as I'm concerned

Stable for sure, but "Tested up to 4.6.6" doesn't sound too "current" :-) But I see what you mean.

The thing is that I have some small (personal) projects that I'm not afraid to use for running development versions of plugins (mostly when I closely follow and/or contribute to the plugin development). Being able to easily keep them up to date with development repos is a great advantage and Composer is an ideal tool for that.

> A composer.json might be an option for the future though.

I'd be happy to submit a PR, if there are no objections. I have [composer.json](https://github.com/chesio/cachify/blob/composer/composer.json) already in a branch of my fork.
