### ISSUE TITLE
Use git tags and GitHub releases for easier comparing of versions

### ISSUE THREAD

**Issue by tyrann0us** [pluginkollektiv/cachify#112]
Hi,
It'll be great to have releases so one could easily compare different versions.
Thanks!

**Comment by krafit** [comment]
Hi @tyrann0us,
as you might know, we make heavy use of git tags in our other plugins (https://github.com/pluginkollektiv/antispam-bee/releases). The day the next Cachify version 
hits, there will be a tag for it! 😄
