### ISSUE TITLE
Unfiy parse_url() usage

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/cachify#118]
In cachify.class.php we are using `wp_parse_url()` while in cachify_hdd.class.php and cachify_memcache.class.php we are using `parse_url()`. We should unify the usage to `wp_parse_url()`

**Comment by chesio** [comment]
Btw. it seems that the second param (`$component`) to the [wp_parse_url](https://developer.wordpress.org/reference/functions/wp_parse_url/) has been introduced only in WP 4.7, so in the moment all calls to `wp_parse_url()` in cachify.class.php will not work in older WordPress versions...

**Comment by krafit** [comment]
Well...  that's bad. Raising the minimum required version to 4.4 is fine, 4.7 is not an option.
Is there a workaround for this?

**Comment by chesio** [comment]
Let's just use the `wp_parse_url` without the `$component`, it's just slightly more code:
```php
// WP 4.7+
$url_path = wp_parse_url( $url, PHP_URL_PATH ) 
// WP 4.4+
$url_parts = wp_parse_url( $url );
$url_path = $url_parts['path'];
```

I believe output should be identical in both cases.
