### ISSUE TITLE
Improve HDD cache expiration UI

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/cachify#121]
#62 added a nice little detail: since the HDD cache can't expire on its own it's pretty pointless to show a expiration option in the backend. We currently show a &#8734; instead. 

![bildschirmfoto 2017-07-03 um 17 52 44](https://user-images.githubusercontent.com/1038789/27800150-6ff86ec2-6018-11e7-8cfe-484004efd47e.png)

Depending on font rendering the &#8734; sometimes looks a bit weird and without further information the user might think of it as a bug. So we could:

a. add a custom icon instead of &#8734; and provide some additional information via tooltip etc.
b. replace the "n Hours" string with something like "HDD cache will not expire on its own"

**Comment by krafit** [comment]
A `disabled` input (+ a description) might be nice a solution as well.

**Comment by chesio** [comment]
> A disabled input (+ a description) might be nice a solution as well.

This might mislead users to believe that HDD Caching expiration time is a constant value that just cannot be changed.

> "HDD cache will not expire on its own"

This is much better in my opinion. Simple and informative.

**Comment by websupporter** [comment]
I would also go with "will not expire on its own".

**Comment by krafit** [comment]
As already stated I'm all pro "will not expire on its own" disclaimer :)
But the disabled input adds a quite pleasing consistency to the UI - in my opinion we should have both,  declaimer and disabled input.

**Comment by websupporter** [comment]
Visualization

*Standard:*
![bildschirmfoto am 2017-07-05 um 08 52 47](https://user-images.githubusercontent.com/6458412/27850792-7d0f4ab6-615f-11e7-8cfe-8ad35722f828.png)

*Only text:*
![bildschirmfoto am 2017-07-05 um 08 53 42](https://user-images.githubusercontent.com/6458412/27850790-7d08afa8-615f-11e7-9c68-06d2b7766d0a.png)

*Disabled input + text:*
![bildschirmfoto am 2017-07-05 um 08 53 04](https://user-images.githubusercontent.com/6458412/27850791-7d0ab7e4-615f-11e7-842f-984227edc1b4.png)

**Comment by krafit** [comment]
Well of cause not as a label but – in a new line 😄

**Comment by krafit** [comment]
So... I spent quit a lot of time thinking about the different solutions to this problem and played around with most of them.

There is one notable interface behavior, I did not completely realize in advance: the interface does not instantly refresh, after the user selects a cache method. Yep, I know, this is no very surprising, since we use plain old HTML for this form. But because the _cache expiration_ option is not hidden instantly the user might still interact with it and change its value.
I don't think removing the input field or the entire cache expiration `<tr>` is the right way to deal with the fact, that we currently can't flush the cache. A disappearing option field can be quite disturbing.

So I refined one of @websupporter's solutions, the "Disabled input Hours + text". In this scenario the disabled input stays visible and serves the purpose of providing a visual clue to the user. In addition I've also removed the value from our disabled input and added a `p.description` this way, core provides us with some nice styling for the description. The description was a little extended and tweaked to explain whats going on.

![bildschirmfoto 2017-07-06 um 15 40 28](https://user-images.githubusercontent.com/1038789/27913801-836c2566-6261-11e7-8df0-fd8c11e46bc6.png)

**Comment by websupporter** [comment]
Looks good to me. I've updated the PR. Basically it prints
```
<td>
    <input min="0" step="1" name="cachify[cache_expires]" id="cachify_cache_expires" value="" disabled="disabled" class="small-text" type="number"> Hours
    <p class="description">HDD cache will only expire as you update posts or flush it yourself.</p>
</td>
```
