### ISSUE TITLE
Check admin notification

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/cachify#122]
I might be wrong on this one, but there is a kind of guideline for these admin nags (or our friend Caspar wrote about it) and we should check them out and see if this nag complies.

![bildschirmfoto 2017-07-03 um 17 50 16](https://user-images.githubusercontent.com/1038789/27800446-b452538e-6019-11e7-8bf6-106c03e52150.png)

**Comment by krafit** [comment]
In fact there are four states for admin notices, as @glueckpress notes in his great post on WP admin notices (german only :/ ) https://glueckpress.com/7471/admin-notices-plugin/

![wp-default-admin-notice-classes-685x530](https://user-images.githubusercontent.com/1038789/27831475-2acb241c-60cb-11e7-9bf0-10463619dbc9.jpg)
Our scenario (asking the user to change their config) seems to be `.notice-warning`

**Comment by bueltge** [comment]
Small hint if you will find the right class, maintain about versions from the wp core - see this plugin as helper https://github.com/bueltge/wordpress-admin-style
