### ISSUE TITLE
Post/Pages-IDs cache exception is not working

### ISSUE THREAD

**Issue by chesio** [pluginkollektiv/cachify#124]
Hi,

besides #123, I just noticed another regression. In 351c48a49daecfacb81dca0cccba3a3d3313bfc6, the last argument (strict checking) has been added to the `in_array` check below (executed [here](https://github.com/pluginkollektiv/cachify/blob/master/inc/cachify.class.php#L1168-L1170)):
```php
if ( in_array( $GLOBALS['wp_query']->get_queried_object_id(), self::_preg_split( $options['without_ids'] ), true ) ) {
  // unreachable code
}
```
As a result, the strict check above will always fail, because `WP_Query::get_queried_object_id()` returns `int`, while `Cachify::_preg_split()` returns array of strings, so the types will never match.

A proper fix in my opinion would be to store `$options['without_ids']` as an array of integers directly in DB, so there's no need to `preg_split`-it on every request, but this would require some fallback (or update routine), so I guess for 2.3.0 a simple fix is to remove the strict check or convert either queried ID to string or the array of IDs to ints.

**Comment by websupporter** [comment]
@chesio thanks for catching that. #129 should fix this bug.
