### ISSUE TITLE
Check setup instructions

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/cachify#136]
as @stklcode stated in #135:
> No, the description is just little confusing.

Let's skim through all our documentation (shipped via `2.3` admin interface) and check for sanity and clear descriptions.

**Comment by stklcode** [comment]
I added some tweaks in the referenced branch.

* replaced confusing "php.ini" reference in nginx APC tab
* highlighting of important lines (PHP FPM endpoint might vary anyway)
* small hint below the code blocks, that some lines might need adjustments (esp. location directives)
* indentation of pre-formatted blocks changed from tab to 2 spaces (the lines are long enough)
* softwraps enabled for code-blocks, as the text ran out of the screen, even at 1280px (scroll bars would be an alternative, but I prefer this)
* minor style tweaks, `<code>` highlighting in notes, ...

Not yet 100% pleased with the instructions and there is still room for improvement (e.g. dynamic templates #138)

**Comment by stklcode** [comment]
I'd consider this issue closed by PR #171.

Above changes have been applied, followup improvements are postponed to 2.4.
