### ISSUE TITLE
Broken gist link

### ISSUE THREAD

**Issue by pixelstrolch** [pluginkollektiv/cachify#153]
Hi folks,
there is a broken link inside your wiki, which shows an example if wp is an subdirectory. The link https://gist.github.com/1949056 is in [General information about Cachify HDD](https://github.com/pluginkollektiv/cachify/wiki/en-Cache-Methods#general-information-about-cachify-hdd). The same in German as well. Thanks!

**Comment by bueltge** [comment]
Thanks @pixelstrolch 
The problem with external content :( I fixed the page, but I haven't an alternate example.
