### ISSUE TITLE
Doesn't work with Chrome ???

### ISSUE THREAD

**Issue by fintinc** [pluginkollektiv/cachify#155]
Hi 
I have a strange issue, as Cachify works as expected with Safari and Firefox but not with Chrome.
The html is not minimized and doesn't show the
```
<!-- Cachify | http://cachify.de
HDD Cache @ 08.05.2018 20:00:19 -->
```
In Safari and Firefox the html is minimized and the Cachify line is added.
The website is https://sneakerness.com

in htaccess I have the following lines:

```
# BEGINN CACHIFY
<IfModule mod_rewrite.c>
    # ENGINE ON
    RewriteEngine On

    # GZIP FILE
    <IfModule mod_mime.c>
        RewriteCond %{REQUEST_URI} /$
        RewriteCond %{REQUEST_URI} !^/(wp-admin|app/cache)/.*
        RewriteCond %{REQUEST_METHOD} !=POST
        RewriteCond %{QUERY_STRING} =""
        RewriteCond %{HTTP_COOKIE} !(wp-postpass|wordpress_logged_in|comment_author)_
        RewriteCond %{HTTP:Accept-Encoding} gzip
        RewriteCond %{DOCUMENT_ROOT}/app/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html.gz -f
        RewriteRule ^(.*) /app/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html.gz [L]

        AddType text/html .gz
        AddEncoding gzip .gz
    </IfModule>

    # HTML FILE
    RewriteCond %{REQUEST_URI} /$
    RewriteCond %{REQUEST_URI} !^/(wp-admin|app/cache)/.*
    RewriteCond %{REQUEST_METHOD} !=POST
    RewriteCond %{QUERY_STRING} =""
    RewriteCond %{HTTP_COOKIE} !(wp-postpass|wordpress_logged_in|comment_author)_
    RewriteCond %{DOCUMENT_ROOT}/app/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html -f
    RewriteRule ^(.*) /app/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html [L]
</IfModule>
# END CACHIFY

```

Is Chrome sending other requests than other browsers ??? 
Has anybody similar issues?
Thanks!

**Comment by fintinc** [comment]
hi @krafit 
sorry I temporarily turned it of yesterday to test some other plugins.
Its on again and you can see different html code in Safari and Chrome, one has the Cachify comment line at the end, the other does not...
thank you!

**Comment by KittMedia** [comment]
Did you clear the cache in Chrome @fintinc ?

I didn’t have any problems viewing a minified version of your website on the latest Chrome on macOS 10.13.4. It seems to working fine, here.

**Comment by krafit** [comment]
Works fine for me as well...

**Comment by fintinc** [comment]
Hi all,
you are right – after a complete restart it works now again on Chrome, so it must have been a problem in Chrome. Of course I cleared the cache, deactivated cache in dev tools, and tried "hard reload and clear cache" before bothering you... 
Thanks very much!
