### ISSUE TITLE
Check for Gutenberg compatibility

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/cachify#161]
WordPress 5.0 will be here soon. Time for us to check, if our plugins are compatible with the Gutenberg Editor and WP 5.0 (a beta version is yet to be published). 

- [x] check (Gutenberg) editor with this plugin
- [x] check plugin settings site with active Gutenberg
- [x] fix potential issues
- [x] add `Tested up to: 5.0` to the plugins readme
- [x] publish changes as minor update or with upcoming plugin update

**Comment by florianbrinkmann** [comment]
I tested saving of options, and if the minimizing option works (it does). I don’t know how to test if the cache is actually created/stored/updated …

**Comment by Zodiac1978** [comment]
`post_submitbox_misc_actions` is not fired anymore. 
https://github.com/WordPress/gutenberg/issues/12764

Therefore our additional settings are not displayed anymore:
https://github.com/pluginkollektiv/cachify/wiki/en-Cache-Methods#control-of-cache-empties-for-article-updates

**Comment by stklcode** [comment]
What about adding this to the global settings like "Default action after saving a post" (clear post, clear all, clear nothing)?
In addition adding a "clear cache or this page" functionality to a submenu for the admin-bar icon (which currently clears the site cache) would also be nice.

I think many users have never used the settings next to the editor anyway (I never did), so in my eyes the above changes would make the clearing functionality more intuitive.
