### ISSUE TITLE
Adding a comment via the backend does not respect comment setting

### ISSUE THREAD

**Issue by florianbrinkmann** [pluginkollektiv/cachify#162]
If the checkbox for clearing the cache when posting a comment is **not** checked, the cache is emptied anyways if a comment is added via the backend (I tested it in the comments view, answering to another comment). Works like expected (not clearing the cache after a new comment) if the comment is added via the frontend.

**Comment by derweili** [comment]
I checked the behavior and can't see any difference between frontend, backend and REST-API.

The cache is flushed for the following events:

- when a comment is add with the status approved
- when a comment changes its status to approved

This also corresponds to the behavior described in the code:
https://github.com/pluginkollektiv/cachify/blob/a3d759774ac6d8591ccada208edb7607a8c82267/inc/cachify.class.php#L117-L126

The mentioned checkbox on the settings page does not control if the cache is flushed or not. Instead it only controls whether the full cache is flushed (the cache of all post/page) or only the cache of post to which the comment belongs.

The cache is not flushed for following events:

- when a comment with a status other than approved is added 
- when a comment changes to status other than approved
- when editing the comment content
- when a comment is deleted

**Comment by florianbrinkmann** [comment]
I just rechecked the behavior and you are right, @derweili, it works like expected. Maybe I did not notice the description text for the checkbox back in the days and just read the label.
