### ISSUE TITLE
Fix PHP 7.2 compatibility

### ISSUE THREAD

**Issue by chesio** [pluginkollektiv/cachify#166]
Since PHP 7.2, [create_function() is deprecated](https://secure.php.net/manual/en/migration72.deprecated.php#migration72.deprecated.create_function-function):

https://github.com/pluginkollektiv/cachify/blob/36c84130ad708abca72683a00875ed7748371692/inc/cachify.class.php#L1194-L1196

**Comment by chesio** [comment]
I don't want to start yet [another thread](https://github.com/pluginkollektiv/antispam-bee/issues/216) on "Should we raise minimum PHP version?", but I'm all for raising minimum required version to PHP 5.3 at least, so issues like this can be fixed with anonymous functions.

**Comment by websupporter** [comment]
I would say go for it. If there is really an installation using 5.2 out there... :scream:

**Comment by 2ndkauboy** [comment]
This could also quite easily fixed with a normal function and then using it's name ;)

**Comment by websupporter** [comment]
This is, what we did in https://github.com/pluginkollektiv/antispam-bee/pull/157 first anonymous than `5.2 compatibility` :see_no_evil: This was the related discussion: https://github.com/pluginkollektiv/antispam-bee/issues/156
Anyway, I would not have a problem with using an anonymous function and by this raising the PHP version.

**Comment by websupporter** [comment]
Thanks for the commit :heart:
