### ISSUE TITLE
Flush Cache automatically when creating/modifying/deleting Terms/Menus

### ISSUE THREAD

**Issue by derweili** [pluginkollektiv/cachify#167]
Currently Cachify auto-flushes the cache on these events:

- After publishing new posts
- After publishing new pages
- After publishing new custom post types
- After publishing new sheduled posts (only Cachify DB)
- After updating WordPress
- If you confirm the trash button on the adminbar

Is there a reason why the cache is not flushed for the following events?
- Menus
  - Creating Menus
  - Editing Menus
  - Deleting Menus
- Terms
  - Creating Terms
  - Editing Terms
  - Deleting Terms

I often have the case users edit Terms or Menus without clicking the Flush Cache Button. (depending on their user role, the Flush Cache Button is hidden so the can't click it)
I know I can extend the Plugin with another plugin but wouldn't it be great if this was a feature inside Cachify?

**Comment by krafit** [comment]
Hi @derweili and thank you for your idea. 
You are right, I also would expect to see the cache flushed for all the events you listed. 

I'm not aware of a reason this is not the case right now, but that shouldn't prevent us from implementing it now.

I'd love to see this in v.2.4 and if you'd like to tinker around with it, feel free do to so, your contribution would be highly appreciated ❤️
