### ISSUE TITLE
Fatal error after update to 2.2.3

### ISSUE THREAD

**Issue by zottto** [pluginkollektiv/cachify#17]
After updating to version 2.2.3 I get the following fatal error:

```Fatal error: require_once(): Failed opening required '/var/www/.../wp-content/plugins/cachify/inc/cachify.class.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/.../wp-content/plugins/cachify/cachify.php on line 88```

Line 81 of cachify.php says
```if ( in_array($class, array('Cachify', 'Cachify_APC', 'Cachify_DB', 'Cachify_HDD', 'Cachify_MEMCACHED')) ) {```

Based on this entries the needed PHP file is loaded from the `inc` directory, but for the first entry `Cachify` there is no corresponing file in `inc/`.

Thanks, Marc

**Comment by Drivingralle** [comment]
Hey!

Thanks for the hint.
We are on it.

Greetings
derRALF

**Comment by Zodiac1978** [comment]
Issue should be fixed. It was a corrupt file upload, please re-install the plugin in a few minutes.
