### ISSUE TITLE
Dashboard widget icon does not match WP 5.3 UI

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/cachify#173]
![Bildschirmfoto 2019-10-05 um 22 48 48](https://user-images.githubusercontent.com/870475/66260705-80acf100-e7c2-11e9-823b-6f5524fcc2ce.png)

In WordPress 5.3 the UI got a facelifting and the colors have more contrast. This does not match with our color for the icon:

`#dashboard_right_now .cachify-icon:before {
 color:#82878c;
 font-family:cachifyIcons
}`

We should omit the color, so that the default color from WordPress is used:

NEW
`#dashboard_right_now li a::before, #dashboard_right_now li span::before, .welcome-panel .welcome-icon::before {
    color: #606a73;
...}`

OLD
`#dashboard_right_now li a::before, #dashboard_right_now li span::before, .welcome-panel .welcome-icon::before {
    color: #82878c;
...}`

The selector is the same.

I've looked for the CSS but did not found it.

**Comment by Zodiac1978** [comment]
Looks like this was changed with Issue #40 and PR #64 

I am not sure how to provide a fallback for older WP versions for this line now:
https://github.com/pluginkollektiv/cachify/blob/510a51088b2ec1bf7427b6d08abb12d323c86f73/css/dashboard.css#L5

**Comment by 2ndkauboy** [comment]
The HTML body has a class `branch-5-3` we could use.

**Comment by 2ndkauboy** [comment]
Or we check the current WordPress Version and if it's smaller then 5.3, we add somd `admin_header` styles with the old color.

We should probably also have a condition for the dark mode ;)

**Comment by Zodiac1978** [comment]
> We should probably also have a condition for the dark mode ;)

You mean for this: https://wordpress.org/plugins/dark-mode/ ?

Or more something like this: https://css-tricks.com/dark-modes-with-css/ ?

**Comment by Zodiac1978** [comment]
> The HTML body has a class branch-5-3 we could use.

Okay, but we need some comparison like <= 5.2 and >5.3 in this case, or not?

I think a simple CSS is not possible in our case. 

> Or we check the current WordPress Version and if it's smaller then 5.3, we add somd admin_header styles with the old color.

I think this is the way we should/need to go here! 👍

**Comment by 2ndkauboy** [comment]
I mean the plugin you have linked. It's still in beta, but I know that people already use it.

The PR should fix both.
