### ISSUE TITLE
Cachify caches state of log in status 

### ISSUE THREAD

**Issue by 00travelgirl00** [pluginkollektiv/cachify#178]
When I open a post while I'm logged in in WordPress and Log out afterwards and open that post again, I still have the state of Loggin, even I have logged out. 

Same Issue happens, when I'm logged in and open a Post I have visit, while was logged out, I see the status, that I'm not logged in. 

The setting for "No cache generation by logged in users" ist not active. 

When I active that setting, the error does not occure. 

Problably the best solution would be to make that setting as default and remove the option.

**Comment by stklcode** [comment]
> The setting for "**No** cache generation by logged in users" ist **not active**

If this is not a typo, Cachify behaves exactly as expected. If you do not want to cache posts for users logged in, you have to enable this option.

**Comment by 00travelgirl00** [comment]
Thanks @stkjj I know that. I just wanted to point out, that this option cause troubles and that we should consider to remove it. We should probably in general not cache lodded in users or at least notify what problems could happen.

**Comment by stklcode** [comment]
There are several use cases for that, so removing is probably not the best way.

On vanilla WP sites it is obviously not perfect. Without the admin bar and JS overlays it might work fine. (although I have to admit that I would not recommend Cachify first place on complex sites)
