### ISSUE TITLE
Use of undefined constant TEMPLATEPATH

### ISSUE THREAD

**Issue by mclucario** [pluginkollektiv/cachify#180]
When I enable cachify on my webpage I get the warning
```Warning: Use of undefined constant TEMPLATEPATH - assumed 'TEMPLATEPATH' (this will throw an Error in a future version of PHP) in .../wp-content/plugins/cachify/inc/cachify.class.php on line 1123```
Is there a fix for this? If not I would try and fix it myself and create a pr.

**Comment by stklcode** [comment]
I assume you're running the latest public release 2.2.4 on current WP 5.3, right?

Issue still present in current _master_ branch:
https://github.com/pluginkollektiv/cachify/blob/a3d759774ac6d8591ccada208edb7607a8c82267/inc/cachify.class.php#L1051

`TEMPLATEPATH` has been deprecated for quite a while<sup>1</sup> and is removed now.

I'd suggest to rework this method to use `get_template_directory()`<sup>2</sup> instead like:
```php
	private static function _is_mobile() {
		$template = get_template_directory();
		return ( strpos( $template, 'wptouch' ) || strpos( $template, 'carrington' ) || strpos( $template, 'jetpack' ) || strpos( $template, 'handheld' ) );
	}
```
(still not very elegant, but it restores current behavior)

[1] https://core.trac.wordpress.org/ticket/18298
[2] https://codex.wordpress.org/Function_Reference/get_template_directory

**Comment by mclucario** [comment]
Thank you
