### ISSUE TITLE
Notice exception after upgrade to v2.3.0

### ISSUE THREAD

**Issue by ffraenz** [pluginkollektiv/cachify#187]
I'm getting following notice exception after the upgrade to version 2.3.0 leading to a white page in my development environment after saving a post:

```
ErrorException: Notice: Undefined index: _cachify_remove_post_type_cache_on_update
#8 /srv/public/content/plugins/cachify/inc/cachify.class.php(916): Cachify::publish_post_types
#7 /srv/public/wp/wp-includes/class-wp-hook.php(287): WP_Hook::apply_filters
#6 /srv/public/wp/wp-includes/class-wp-hook.php(311): WP_Hook::do_action
#5 /srv/public/wp/wp-includes/plugin.php(478): do_action
#4 /srv/public/wp/wp-includes/post.php(4691): wp_transition_post_status
#3 /srv/public/wp/wp-includes/post.php(4045): wp_insert_post
#2 /srv/public/wp/wp-includes/post.php(4235): wp_update_post
#1 /includes/post.php(409): edit_post
#0 /post.php(227): null
```

Also I noticed that the button to configure caching for a specific post vanished which is probably connected to this issue. As this project adheres to semantic versioning I would consider this a bug because I didn't expect breaking changes with this update. Am I missing something?

**Comment by stklcode** [comment]
Good catch. The specific option per page is gone in davor of the global settings flag how to react on saved posts (see #176).

Gonna remove the remaining dirt, as it does not have any effect on the plugin behavior.

**Comment by ffraenz** [comment]
Looks awesome! Thank you!

**Comment by ffraenz** [comment]
Hi @stklcode! Is there any time schedule about when this fix is set to be released? I'd like to update the plugin on several WordPress installations. Thank you!
