### ISSUE TITLE
Cachify V2.3.0 Only 2 cache mode can be used ？

### ISSUE THREAD

**Issue by ixmu** [pluginkollektiv/cachify#196]
![TIM截图20200705113137.jpg](https://kyun.ltyuanfang.cn/tc/2020/07/05/ae6241f84020a.jpg)
Cachefy v2.3.0 can only use 2 cache mode？

**Comment by stklcode** [comment]
I can't read the screenshot, but I guess the two methods are DB and HDD.

These two are always available. Memcached and APC require the corresponding PHP extensions to be installed and enabled on your system. Is that the case?

**Comment by ixmu** [comment]
> I can't read the screenshot, but I guess the two methods are DB and HDD.
> 
> These two are always available. Memcached and APC require the corresponding PHP extensions to be installed and enabled on your system. Is that the case?

> 我看不到截图，但是我猜这两种方法是DB和HDD。
> 
> 这两个始终可用。Memcached和APC需要在系统上安装并启用相应的PHP扩展。是这样吗

你的猜测是正确的，非常感谢
Your guess is correct. Thank you very much
