### ISSUE TITLE
add option to disable GZ compression for HDD caching

### ISSUE THREAD

**Issue by stklcode** [pluginkollektiv/cachify#197]
Related to request from WP support forums: https://wordpress.org/support/topic/disable-gz/

The HDD caching module always generates a static HTML file along with a gzipped version:
https://github.com/pluginkollektiv/cachify/blob/dcac6b7babdef4454782faf6f9c076699cb11944/inc/cachify_hdd.class.php#L165-L166

We have a corresponding block in the Apache HTTP server example using _mod_mime_ to server the pre-compressed content.

With most webservers supporting compression natively which can be superior to compression by PHP and more important is not handled during initial site visit, many sites don't need the explicit _*.gz_ files.

We should at least introduce an option to disable generation of pre-compressed files to reduce the overhead here.

**Comment by pfefferle** [comment]
What about trying to detect if gzip is enabled, to automatically deactivate the encoding?

**Comment by angcl** [comment]
#262 This PR addresses this issue.
