### ISSUE TITLE
Be protocol-agnostic

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/cachify#2]
Although accessing a site over both HTTP and HTTPS isn't really recommended, the plugin currently doesn't work in this scenario ([see this support request](https://wordpress.org/support/topic/separate-caches-for-http-and-https?replies=2)).

The following changes need to be made:

* Take protocol into account in [`Cachify::_cache_hash`](https://github.com/pluginkollektiv/cachify/blob/master/inc/cachify.class.php#L1082) method.
* Take protocol into account in [ `Cachify_HDD::_file_path`](https://github.com/pluginkollektiv/cachify/blob/master/inc/cachify_hdd.class.php#L344) method
* Add protocol to `.htaccess` rewrite rules

**Comment by swissspidy** [comment]
I'd like to take a step back here.

The change proposed in #3 doesn't seem to be very backwards compatible. The old cache without the prefix wouldn't get deleted.

Also, with HTTP/2 coming up, I really recommend going HTTPS-only.

**Comment by glueckpress** [comment]
@swissspidy Does this need any dev feedback? I’m afraid I can’t contribute here. :wink:

**Comment by swissspidy** [comment]
@glueckpress I'll have a look at this again when I get a chance.

**Comment by COLABORATI** [comment]
Hi, would you please like to add this commit to the official plugin release? I am also waiting for this, as this bug is quite annoying and I do not want to maintain that code changes manually. Thanks!

**Comment by glueckpress** [comment]
@COLABORATI Wich one exactly?

**Comment by swissspidy** [comment]
I'll have another look at the pull requests in February

**Comment by skalscheuer** [comment]
I totally agree with you to prefer HTTPS-only pages, but this decision is not to be made by a plugin like cachify. Imho the plugin should be able to handle mixed protocols.

Code perfo is not the issue here and the drawback of doubled memory consumption is acceptable (at least not your biggest problem at this point). I'm using a modified version like PR#20 (trivial solution) and it does the job quite well.

**Comment by COLABORATI** [comment]
Why no progress here? Why? Please explain. Thanks.

**Comment by swissspidy** [comment]
@colaborati mainly because of lack of time and none of the pull requests being exactly what we should have in the plugin. We all do this in our spare time, so please be patient with us. If you wanna help out that would be highly appreciated

**Comment by stklcode** [comment]
I just created a new PR #41 based on my previous comment. I'm using this version since approx. 5 months in production without any problems.
