### ISSUE TITLE
Flush cache overwork

### ISSUE THREAD

**Issue by timse201** [pluginkollektiv/cachify#223]
Right now the entire cache is cleared when
user_register - don't know why
edit_user_profile_update - why should it clear all and not it's own profile page cache
delete_user - makes sense if there is a link to the profile

and add some third parties:
_to clear entire cache:_
autoptimize_action_cachepurged
_when needed:_
woocommerce_product_set_stock
woocommerce_variation_set_stock
woocommerce_product_set_stock_status
woocommerce_variation_set_stock_status

**Comment by stklcode** [comment]
> edit_user_profile_update - why should it clear all and not it's own profile page cache

User names are potentially displayed on very post, page or comment as author reference. Collecting all affected pages, including archives, summaries, widgets, etc. seems overdone.
