### ISSUE TITLE
"Flush cache now" button contrast

### ISSUE THREAD

**Issue by derweili** [pluginkollektiv/cachify#227]
The "Flush cache now" button has a orange background with white text. This is a small contrast ratio of 2.86.

see: https://colourcontrast.cc/dd823b/ffffff

**Comment by stklcode** [comment]
It's partially compensated by the text shadow. Without it's definitely bad contrast.

![cachify_btn_shadow](https://user-images.githubusercontent.com/12963621/117868446-e95f2800-b299-11eb-8bc4-5b5703ff1c57.png)
(left: with shadow, right: without)

I personally dislike the shadow though. If we stick to the WP 5.7 admin color palette, red 50/60 (default / hover) would be an alternative or - I'd personally prefer this - default blue border with trash icon
![cachify_btn_alt](https://user-images.githubusercontent.com/12963621/117869757-7f478280-b29b-11eb-9dfd-69062dfd9482.png)

**Comment by derweili** [comment]
@stklcode I also prefer the blue border button with the trash icon.

The red button looks more like a "Clear all plugin data" button.

**Comment by stklcode** [comment]
Definitely, yes. I also tried yellow-combinations to stay in line with WP admin colors, but in the end all full-colored versions do look like some kind of warning or dangerous button while the flush cache link in the admin bar does not - and both do the very same.
