### ISSUE TITLE
Multisite, activatd by-site: clearing HDD cache clears the entire network cache

### ISSUE THREAD

**Issue by mcguffin** [pluginkollektiv/cachify#23]
A blog admin is able to clear all other sites caches as well. 
Same may be true for Memcache, APC and DB cache.

**Comment by mcguffin** [comment]
See pr #24

**Comment by websupporter** [comment]
I just had a look into this issue. It is still reproducible with our current `master` version. I will dive into #24 quickly to see, if this solves the issue. Thanks @mcguffin for reporting this and sorry it took more than a year to really dive into this issue. :heart:
