### ISSUE TITLE
WordPress Core sitemaps are cached (and served with the wrong content type when using HDD caching)

### ISSUE THREAD

**Issue by ManuelHu** [pluginkollektiv/cachify#242]
**Describe the bug**
Since Wordpress 5.5 there is [a sitemap feature included in Core](https://make.wordpress.org/core/2020/07/22/new-xml-sitemaps-functionality-in-wordpress-5-5/). When using HDD Caching those sitemaps will be served as text/html (as they are cached in a .html file) instead of the correct type application/xml.

**To Reproduce**
1. Install Cachify
2. Enable HDD caching & add the provided snippet to .htaccess
3. Visit `/wp-sitemap.xml` (Content-type: application/xml)
4. Reload page, it should display the cached version with the wrong content type (=> Content-type: text/html)

**Expected behavior**
Sitemaps are either not cached at all or served with the correct content type.

Currently RSS feeds are not cached, so sitemaps should probably be excluded to exclude all core-generated non-html content?

**System (please complete the following information):**
- Version 2.3.1 / WordPress 5.8.1

**Additional context**
The following code works to detect all sitemaps and the corresponding XSL style sheets:

```
add_filter(
	'cachify_skip_cache',
	function() {
		global $wp_query;
		return ! empty( $wp_query->query_vars["sitemap"] ) ||
			! empty( $wp_query->query_vars["sitemap-subtype"] ) ||
			! empty( $wp_query->query_vars["sitemap-stylesheet"] );
	}
);
```

**Comment by chesio** [comment]
To avoid directly accessing global `$wp_query` one can use [get_query_var](https://developer.wordpress.org/reference/functions/get_query_var/):
```php
... get_query_var('sitemap') ...
... get_query_var('sitemap-subtype') ...
... get_query_var('sitemap-stylesheet') ...
```
