### ISSUE TITLE
Redis: New feature with pull request

### ISSUE THREAD

**Issue by newtovaux** [pluginkollektiv/cachify#253]
**Describe the feature**
Whilst Memcached is popular, Redis is increasing in support within the Web Hosting and Containter Hosting ecosystems.

Although they are both easy to use and offer high performance; Memcached is designed for simplicity while Redis offers a rich set of features that make it effective for a wide range of use cases.

**Pull Request**
I have created a Pull Request [https://github.com/pluginkollektiv/cachify/pull/252](https://github.com/pluginkollektiv/cachify/pull/252) to add the Redis feature, based largely on the Memcahed design.

**Comment by krafit** [comment]
Hi @newtovaux thank you for this. This looks very promising to me. I‘ll ask a couple of my teammates to review your PR, but Redis support seems like a genuinely useful new feature moving forward.
