### ISSUE TITLE
Styling for dark mode plugin that is a Markdown editor now

### ISSUE THREAD

**Issue by florianbrinkmann** [pluginkollektiv/cachify#264]
A few years ago a style modification for the dashboard icon was added to look good when used with a dark mode plugin. That plugin contains a markdown editor now and does not call the filter that was used back then. Should we just remove the style modification or keep it for users that stick with the old dark mode plugin version?

We (@angelocali and I) also thought about adding support for the latest version of the plugin, because besides the markdown editor option (that is a paid feature only), the dark mode is still there. But then we decided to not add it, because rebranding a plugin from dark mode to markdown editor is a little bit creepy and nothing we wanted to add support for.

**Comment by krafit** [comment]
I'd opt to remove the style modification. The mentioned dark mode plugin had potential back in the day but that's a thing of the past.

**Comment by Zodiac1978** [comment]
To add some more data:

This is the plugin data page: https://de.wordpress.org/plugins/dark-mode/advanced/

It has 3000 active installations. 16,2 % is version 3, 9,3 % is version before v3, the rest is v4 or higher (markdown editor came with v4).

This ends up to 765 users having a version which is still using the filter.

+1 form me for not adding the filter anymore.

**Comment by Zodiac1978** [comment]
If we want to support dark mode there more plugins that will do that:
https://de.wordpress.org/plugins/search/dark+mode/

And at least some of them also support dark mode for the admin area:
https://wordpress.org/plugins/droit-dark-mode/
https://wordpress.org/plugins/dark-mode-for-wp-dashboard/
https://wordpress.org/plugins/darklup-lite-wp-dark-mode/

But I still think this is not very necessary. The biggest amount of active installs is the first one with 4k, then 1k and 400.
The question never came up in the forums.
