### ISSUE TITLE
404s for missing gists, dead links, missing posts on G+ in wiki

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/cachify#35]
There are many dead links, mostly missing gists. I just collected the snippet/line and the link here:
## 404s in https://github.com/pluginkollektiv/cachify/wiki/Caching-Methoden

Dies geschieht durch eine Erweiterung der Apache-Datei .htaccess oder der Nginx-Konfigurationsdatei.
http://playground.ebiene.de/nginx-wordpress-optimieren/

Erweiterung der .htaccess (Apache) (https://gist.github.com/sergejmueller/2027249#file-htaccess)

Ist in WordPress das WPTouch-Plugin (oder ein anderes Mobile-Plugin) installiert, müssen RewriteRules erweitert werden, siehe Gist.
https://gist.github.com/sergejmueller/a15b7377fde8453893f3

Das HDD-Caching in Cachify kann nur bei aktivierten WordPress-Permalinks ausgewählt und genutzt werden. Ein Schrägstrich am Ende des Permalinks wird ebenfalls vorausgesetzt. Für Permalinks ohne Slash am Ende ist die Nutzung eines spezielle .htaccess-Snippets vonnöten. Der Snippet-Code ersetzt den oben vorgestellten .htaccess-Eintrag.
https://gist.github.com/sergejmueller/5398472

Befindet sich der Blog in einem Unterverzeichnis und die dazugehörige .htaccess außerhalb des Blog-Verzeichnisses, gehört der Pfad zum Cache-Ordner angepasst. Beispiele als Gist.
https://gist.github.com/1949056

Die eingestellte Cache-Gültigkeitsdauer kann nicht einbezogen werden. Muss der Cache-Bestand in bestimmten Zeitabständen geleert werden, so empfiehlt sich der Aufruf einer präparierten PHP-Datei per Cronjob.
https://gist.github.com/sergejmueller/5412991
## 404s in https://github.com/pluginkollektiv/cachify/wiki/Einstellungen

Erweiterung der Ausnahmeliste für einzelne Blogseiten. Eine Komma-separierte Liste an Post- und/oder Page-IDs, die vom Cache ausgeschlossen werden sollen.

Integrierter Filter: cachify_skip_cache
https://gist.github.com/sergejmueller/6990637
## 404s in https://github.com/pluginkollektiv/cachify/wiki/Funktionsweise

Beim Speichern von Cachify– und wpSEO-Optionen
https://plus.google.com/b/106964298865639944324/

**Comment by timse201** [comment]
not dead but old links:
https://github.com/pluginkollektiv/cachify/wiki/de-Unterst%C3%BCtzung

all fine with them or should we only add the PayPal Link from the readme?

**Comment by patrickrobrecht** [comment]
Checked and moved remaining (and some new) issues at our documentation site to #204. Wiki links to the documentation site now.
