### ISSUE TITLE
Toolbar: Too generic CSS class "ab-icon" for trash icon

### ISSUE THREAD

**Issue by tyrann0us** [pluginkollektiv/cachify#37]
The CSS class for specifiying the trash dashicon is `ab-icon`. This seems to be too generic since other plugins/themes might use the same class and thus get a wrong icon. Better use `dashicons-trash`.

Example plugin: [The Events Calendar](https://wordpress.org/plugins/the-events-calendar/).

**Comment by swissspidy** [comment]
Thanks for your report!

I will close this as a duplicate of #25 which already fixed this bug.

We're planning to release a maintenance release soon which will include this fix.

**Comment by tyrann0us** [comment]
Sorry, I missed this one.

**Comment by swissspidy** [comment]
No problem, I'm glad you took the time to report it anyway :)
