### ISSUE TITLE
Flush cache if option is enabled and comment is from backend

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/cachify#4]
We just flush the cache if a comment is made in the frontend, but comments can be made from the backend too.
See: https://github.com/pluginkollektiv/cachify/blob/7689f556ee0c85de554bbc2a865a2d59852d6422/inc/cachify.class.php#L251

**Comment by swissspidy** [comment]
Hmm the hook doesn't look too bad but maybe we should switch to a later hook.

Can you try changing the hook on that line to `comment_post` or maybe `wp_insert_comment` and test it again?

**Comment by Zodiac1978** [comment]
I think, the hook is not the problem, it is the conditional tag is_admin from line https://github.com/pluginkollektiv/cachify/blob/7689f556ee0c85de554bbc2a865a2d59852d6422/inc/cachify.class.php#L153 - we are in the "else" part of that check, so this hook is just used if it is "! is_admin" and I think, that is the problem. Or am I wrong?

**Comment by swissspidy** [comment]
Oh, right. My bad. I haven't looked at the surrounding lines.

**Comment by Zodiac1978** [comment]
No problem :) 

So just copy this block to the if-part too? Or is there a more elegant way to solve this?

**Comment by swissspidy** [comment]
Before the if/else block ;)

**Comment by Zodiac1978** [comment]
Of course ... m( :)

**Comment by Zodiac1978** [comment]
@swissspidy and all: Could you test this commit. Works for me now.

**Comment by swissspidy** [comment]
@Zodiac1978 Well, now it's already committed anyway ;) Looks good to me.
