### ISSUE TITLE
Convert icon font to SVG

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/cachify#40]
SVG files are considered superior nowadays compared to icon fonts.

See: https://github.com/pluginkollektiv/cachify/blob/7689f556ee0c85de554bbc2a865a2d59852d6422/css/dashboard.css#L5

See also #39.

**Comment by 2ndkauboy** [comment]
I totally agree. Does anyone knows how to extract the vector graphic from an opentype font? Using the SVG than instead of the font should be easy.

**Comment by swissspidy** [comment]
Looks like there are some online font->svg converter tools around
