### ISSUE TITLE
Guided Tour for Beginners

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/cachify#43]
After the first installation, we should guide the user to explain the different settings and perhaps even recommend a specific caching method, etc.

IIRC WooCommerce and Yoast SEO have such tours at the beginning.

**Comment by tyrann0us** [comment]
To be honest, what I like about Cachify is it's simplicity and lack of multiple options pages, ads and tours.

For me this plugin is mainly meant for people who know what they do.
"WordPress beginners" on the other hand can choose from a wide range of caching plugins which have tours, intros and nagging admin notices.

**Comment by timse201** [comment]
dont like such tours, too
think a better solution is to add some small info icons with some hints if you hover them

**Comment by herrbischoff** [comment]
Please don't add *any* kind of cruft to the plugin. I consider this to be a "pro" plugin, not a "consumer" one.

**Comment by swissspidy** [comment]
Note that this was just a suggestion in order to reduce support requests because people often have no idea how to configure Cachify.

**Comment by herrbischoff** [comment]
Users are always going to find a way to not get, not read or even break something in ways you could never anticipate. Going for the lowest common denominator (attention span of a narcoleptic panda bear) is the wrong approach. Words have meanings and people need to read them.

The best way would be a little reminder in the settings to "take a minute to set it up" with a link to the documentation. Even better: *include* the documentation!
