### ISSUE TITLE
dont work with https-Site anymore

### ISSUE THREAD

**Issue by sysmek** [pluginkollektiv/cachify#44]
dont work with https-Site anymore

cache is writen to / wp-content / cache / cachify / https-webseite.de / 
but is not in use by reading a page. 

since version 2.2.4

**Comment by swissspidy** [comment]
Thanks for your report.

This was a tough decision to make because lots of people seem to use both https and http.

You'd have to change your `.htaccess` file to adjust for the `https-` part. See #3 for a discussion / suggested solution.

We'll have to get our documentation updated quickly.

**Comment by sysmek** [comment]
i use nginx, 
is there a new rule out there ?

**Comment by swissspidy** [comment]
If your site is HTTPS-only, you can try replacing

```
try_files /wp-content/cache/cachify/${host}${uri}index.html @nocache;
```

with

```
try_files /wp-content/cache/cachify/https-${host}${uri}index.html @nocache;
```

in your nginx config.

If you use HTTPS and HTTP on the same site, it would be something like

```
if ($scheme != 'https') {
    try_files /wp-content/cache/cachify/${host}${uri}index.html @nocache;
}

try_files /wp-content/cache/cachify/https-${host}${uri}index.html @nocache;
```

or perhaps even

```
try_files /wp-content/cache/cachify/https-${host}${uri}index.html /wp-content/cache/cachify/${host}${uri}index.html @nocache;
```

**Comment by sysmek** [comment]
thank you very match! it's working fine now with:
`try_files /wp-content/cache/cachify/https-${host}${uri}index.html /wp-content/cache/cachify/${host}${uri}index.html @nocache;`
