### ISSUE TITLE
HDD cache not working with HTTPS

### ISSUE THREAD

**Issue by hostz-frank** [pluginkollektiv/cachify#46]
https://wordpress.org/support/topic/pages-are-cached-on-hdd-properly-but-not-found-in-https-sites

Does not cache nada. 

Ärgerlich. 
Steht seit 2 Wochen im WP-Forum...

Please fix.

**Comment by Zodiac1978** [comment]
You have to update your .htaccess and add the `https-`prefix.
See https://github.com/pluginkollektiv/cachify/issues/44 for a nginx example.

**Comment by hostz-frank** [comment]
I did already. I wonder how this change would work for mixed protocol site (that's what you fixed, right?). 

Looks messy to me.

**Comment by swissspidy** [comment]
What exactly is messy about supporting mixed-protocol setups? Running one is probably messy, but we have to provide a working solution for our users.

If you say "does not cache nada" and "I did already", can you please tell us what exactly you changed in your site configuration and what exactly is not working? Sharing your nginx / .htaccess config would be very helpful.

**Comment by hostz-frank** [comment]
Messy is excactly this: imagine you're using Cachify for years. Then you make an update. Then it stops working.
No notice after the update process. No warning that you need to update server config files when you use HDD cache. No hint in documentation. This is a reason to switch ton another file cache - there are lots of them. You play with user trust, boys. I'm not crying about open source software. I cry about the style of how cool to serve messy software to people using the standard WordPress update process.

> If you say "does not cache nada" and "I did already"

I did not say this at the same time, but the second cite I made after days of figuring out by myself.

**Comment by swissspidy** [comment]
> Messy is exactly this: imagine you're using Cachify for years. Then you make an update. Then it stops working.

That's not messy, it's a break of backward compatibility for some of our users. For some other users, we fixed an annoying bug. Believe me, if I know one thing about WordPress, its ecosystem and user experience in general, it's that such breakage is bad.

> No notice after the update process. No warning that you need to update server config files when you use HDD cache. No hint in documentation. This is a reason to switch to another file cache - there are lots of them.

We're in the middle of updating all our plugins and documentation. Please allow us some time to investigate this further and come up with solutions. We all do this in our spare time, and everybody makes mistakes. If you want to switch to another caching solution, nobody prevents you. If you want to help make this plugin better, great.

> You play with user trust, boys. I'm not crying about open source software. I cry about the style of how cool to serve messy software to people using the standard WordPress update process.

Let's keep a friendly tone here, thanks.

I'm closing this issue now as the problem has been resolved. Again, we continue to work on an update.

**Comment by Zodiac1978** [comment]
Let's aim to be better next time. No one is perfect.

@swissspidy We can add an upgrade notice in the next update and add some documentation to the mentioned wiki page. Is it possible to have a link in the upgrade notice so we can point the users to the wiki? (at least for the German speaking users)
