### ISSUE TITLE
English support for setting up the .htaccess file with the different cache options (HDD, APC, Memcached)

### ISSUE THREAD

**Issue by mkormendy** [pluginkollektiv/cachify#48]
I can't understand the google English translations of the content for this plugin.

**Comment by swissspidy** [comment]
Hey there,

Which content are you referring to? The wiki here on GitHub or some text inside the plugin when in your WordPress admin?

**Comment by mkormendy** [comment]
github

**Comment by mkormendy** [comment]
As well the installation section on the Wordpress Hosted Plugin page, doesn't really go into detail on how to configure the htaccss for the HDD option.

**Comment by swissspidy** [comment]
Thanks for clarifying! This is actually some very important feedback.

Originally, the whole documentation was in German. We slowly started translating every bit of it. The GitHub wiki is one of the last bigger pieces we hope to get to soon.

In addition to that, you're absolutely right that we should improve documentation on WordPress.org, though we most likely will link to the (by then translated) documentation here on GitHub.

We'll let you know as soon as we finished this. Until then, let us know if we can help you with configuring your `.htaccess` file.

Hope that helps.

**Comment by mkormendy** [comment]
Okay, in that case how do I configure the .htaccess file for the three different options?

**Comment by swissspidy** [comment]
Sure. So for **APC**, you only need to add the following line to the top of that file:

```apache
<Files index.php>
    php_value auto_prepend_file /path/to/wp-content/plugins/cachify/apc/proxy.php
</Files>
```

**Memcached** is currently only supported in combination with nginx because of some limitations in Apache2 that wouldn't really help speed up your site.

For hard disk cache you need some more configuration:

```apache
# BEGIN CACHIFY
<IfModule mod_rewrite.c>
    # ENGINE ON
    RewriteEngine On

    # GZIP FILE
    <IfModule mod_mime.c>
        RewriteCond %{REQUEST_URI} /$
        RewriteCond %{REQUEST_URI} !^/wp-admin/.*
        RewriteCond %{REQUEST_METHOD} !=POST
        RewriteCond %{QUERY_STRING} =""
        RewriteCond %{HTTP_COOKIE} !(wp-postpass|wordpress_logged_in|comment_author)_
        RewriteCond %{HTTP:Accept-Encoding} gzip
        RewriteCond %{DOCUMENT_ROOT}/wp-content/cache/cachify/%{HTTP_HOST}%{REQUEST_URI}index.html.gz -f
        RewriteRule ^(.*) /wp-content/cache/cachify/%{HTTP_HOST}%{REQUEST_URI}index.html.gz [L]

        AddType text/html .gz
        AddEncoding gzip .gz
    </IfModule>

    # HTML FILE
    RewriteCond %{REQUEST_URI} /$
    RewriteCond %{REQUEST_URI} !^/wp-admin/.*
    RewriteCond %{REQUEST_METHOD} !=POST
    RewriteCond %{QUERY_STRING} =""
    RewriteCond %{HTTP_COOKIE} !(wp-postpass|wordpress_logged_in|comment_author)_
    RewriteCond %{DOCUMENT_ROOT}/wp-content/cache/cachify/%{HTTP_HOST}%{REQUEST_URI}index.html -f
    RewriteRule ^(.*) /wp-content/cache/cachify/%{HTTP_HOST}%{REQUEST_URI}index.html [L]
</IfModule>
# END CACHIFY
```

If your site's running on HTTPs, replace `/wp-content/cache/cachify/%{HTTP_HOST}%{REQUEST_URI}index.html` with `/wp-content/cache/cachify/https-%{HTTP_HOST}%{REQUEST_URI}index.html`

**Comment by mkormendy** [comment]
Thank you! So I had the first one already done based on a post I read, I didn't know if there was something different.

The reason why I came back, or thought that there might be something different is because I have a really long TTFB (3+ seconds for 784KB). I was hoping that this plugin would help since I am using APCu on my apache server. I also have opcache as well, both are working.

Now I've read about putting varnish and nginx in front of apache as a reverse proxy for static files. How would that affect this plugin? Would it help? Does there need to be further configuration?

**Comment by swissspidy** [comment]
> If my HDD is SSD, would APC or HDD be faster?

There are lots of different factors playing a role here, but HDD is often faster under many conditions.

> Now I've read about putting varnish and nginx in front of apache as a reverse proxy for static files. How would that affect this plugin? Would it help? Does there need to be further configuration?

Good questions! So if your site's running on HTTPS you'd need nginx in front of Varnish for HTTPS termination. Varnish can then do all the caching and pass back to nginx for calling PHP if necessary. No need to bring Apache2 into this, it only makes things more complex.

You won't need a plugin like Cachify at all if you have Varnish caching all the things. All you'd need is something like the [Varnish HTTP Purge](https://wordpress.org/plugins/varnish-http-purge/) plugin. With that being said, nginx can do full page caching as well ([here's an example](https://gist.github.com/markjaquith/04162825d159c8fb5534)), so there's not really a need for Varnish either.

**Comment by mkormendy** [comment]
Okay great, thanks! You probably should copy and paste your answers here (with minor modification) onto the WordPress Plugin Page Installation tab. It'll save you some time having to answer questions from people like me :-)

**Comment by timse201** [comment]
https://github.com/pluginkollektiv/cachify/wiki

Wiki is now translated - german, english is now provided

(please note i'm not part of pluginkollektiv and my mother tongue is german if you find some parts which are not well translated please let me/us know)

**Comment by bueltge** [comment]
Thanks again @timse201 :heart: 

Please look at now also at the new navigation inside the wiki, please add new pages also in this nav structure.

**Comment by timse201** [comment]
edited some parts to clarify:
Extension of the _.htaccess_ (Apache)
to
**A description for only https and sites that are accessible via https and http follows below.**
Extension of the _.htaccess_ (Apache), if the website is only accessible via http: (https://gist.github.com/sergejmueller/2027249#file-htaccess)

edited:
_.htaccess_ extension for websites that can be reached under both `http` and` https`: (https://gist.github.com/mcguffin/31f80070d631d56da23cefb4ef1b6649)
to
_.htaccess_ extension for websites that can be reached under both **`http` and` https`**: (https://gist.github.com/mcguffin/31f80070d631d56da23cefb4ef1b6649)

and added behind _Notes about .htaccess customizations_
* If the website **is only accessible via SSL/TLS**, you must edit `/wp-content/cache/cachify/%{HTTP_HOST}%{REQUEST_URI}index.html` to /wp-content/cache/cachify/**https-**%{HTTP_HOST}%{REQUEST_URI}index.html

german wiki, too
