### ISSUE TITLE
»Das Plugin hat keinen validen Header.« at activation from plugin installation screen

### ISSUE THREAD

**Issue by FlorianBrinkmann** [pluginkollektiv/cachify#50]
After installing the plugin and trying to activate it directly from the search results I get the error »Das Plugin hat keinen validen Header.«. This is only the case if I activate it from the plugin installation screen. If I try it via the installed plugins list, it works fine…

**Comment by Zodiac1978** [comment]
Thanks for more insights!

First reported here:
https://wordpress.org/support/topic/wordpress-error-plugin-does-not-have-a-valid-header/

**Comment by Zodiac1978** [comment]
I cannot reproduce this on my test system. Can you @FlorianBrinkmann provide us with more information about your environment? PHP version? etc. Thank you!

**Comment by FlorianBrinkmann** [comment]
Of course. I tried it with two installations – 4.6.1 and trunk. Both on Uberspace with PHP 7.0.11.

That’s how it looks like (current trunk):

![cachify](https://cloud.githubusercontent.com/assets/2310924/20705759/8bc73f1e-b624-11e6-95af-e8d939c9091c.gif)

No entry in error log…

**Comment by Zodiac1978** [comment]
Still no luck in reproducing the problem. PHP 7.0.6 with 4.6.1 and trunk - no problems here.

Which hoster are you using?

**Comment by FlorianBrinkmann** [comment]
Uberspace :)

**Comment by Zodiac1978** [comment]
If you can read ... 🙈 Thx and sorry! :)

**Comment by FlorianBrinkmann** [comment]
😄 no problem

**Comment by timse201** [comment]
with lima-city too
php 5.6

**Comment by buddhaplautze** [comment]
same with Linode and PHP 7.0

**Comment by timse201** [comment]
got it :)

when downloading in wordpress itself the folder trunk is in the plugin dir. WordPress trys to activate trunk while in installation. If you go to plugins and activate it there it works because it activates the "stable" version.

i deleted the folder trunk on the server and tried to activate it (under plugins/installation) and it worked

_plugin content:_
apc
css
inc
js
trunk (needs to be deleted)
cachify.php
CHANGELOG.md
readme.txt

**Comment by Zodiac1978** [comment]
Nice catch!

**Comment by swissspidy** [comment]
Crap, how did the trunk folder get into the tag?! Looks like I'm the one to blame :(

I removed it now from subversion, so this should be good again.
