### ISSUE TITLE
More Screenshots on WordPress.org

### ISSUE THREAD

**Issue by timse201** [pluginkollektiv/cachify#57]
at the moment there is only 1 picture on WordPress.org
https://ps.w.org/cachify/assets/screenshot-1.png?rev=976963

There sould be more screenshots
like:
https://github.com/pluginkollektiv/assets/raw/master/cachify/images/cachify-toolbar-icon.png
https://www.pc-tweak.de/entwicklung/publish-remove.png
https://www.pc-tweak.de/entwicklung/settings.png

[#1 assets](https://github.com/pluginkollektiv/assets/pull/1)

**Comment by Zodiac1978** [comment]
The idea is great, but the quality of the images is bad. Even the Icons in the dashboard are looking bad. 

Here are some screenshots from me:
![bildschirmfoto 2017-01-07 um 02 28 19](https://cloud.githubusercontent.com/assets/870475/21738155/0efd39b8-d481-11e6-90c6-b587ca172bbc.png)
![bildschirmfoto 2017-01-07 um 02 27 22](https://cloud.githubusercontent.com/assets/870475/21738157/0f07331e-d481-11e6-9a96-43cdf23b926b.png)
![bildschirmfoto 2017-01-07 um 02 27 10](https://cloud.githubusercontent.com/assets/870475/21738156/0f04f78e-d481-11e6-9002-52e0e23885fd.png)
![bildschirmfoto 2017-01-07 um 02 26 52](https://cloud.githubusercontent.com/assets/870475/21738158/0f094f14-d481-11e6-8135-4a09fc8cde2b.png)

**Comment by timse201** [comment]
Yes i weboptimzed them to reduze size
Thought that s.o. could load it with mobile devices

**Comment by websupporter** [comment]
Since #108 we have a new option in 2.3.0 on the settings page. Here an updated screenshot:
![bildschirmfoto am 2017-07-03 um 17 45 25](https://user-images.githubusercontent.com/6458412/27797771-7e601f42-6017-11e7-8f40-b7873aa69761.png)

**Comment by krafit** [comment]
@websupporter yep, got this on my list. But I'm not entirely pleased with the current state of the backend. Some bits and pieces still need a little love, to get `2.3.0` out.

**Comment by 00travelgirl00** [comment]
How about this screenshot? The UI changed a bit already and it looks pretty smooth to me. 


<img width="877" alt="bildschirmfoto 2017-11-21 um 21 44 58" src="https://user-images.githubusercontent.com/21318377/33098482-771e95f8-cf05-11e7-859a-0d07128bc26b.png">

**Comment by stklcode** [comment]
Some Screenshots from the current master branch 2.3.0 RC on a vanilla WP 5.2 test site.

Dashboard Widget:
![dashboard-widget](https://user-images.githubusercontent.com/12963621/58903599-1b5acd80-8706-11e9-8e66-ec71372dd16a.png)

Settings Page:
![settings-page](https://user-images.githubusercontent.com/12963621/58903614-231a7200-8706-11e9-84db-213546ca5bd2.png)

Flush Cache Button in Toolbar:
![toolbar-flush-cache](https://user-images.githubusercontent.com/12963621/58903632-2f063400-8706-11e9-82b8-d6f5711b405b.png)
