### ISSUE TITLE
Broken Link in Wiki

### ISSUE THREAD

**Issue by pixolin** [pluginkollektiv/cachify#6]
Just stumbled upon a broken link in the Wiki:

*Wiki-Page*: https://github.com/pluginkollektiv/cachify/wiki/Caching-Methoden 
*Context*: Einige (wenige) Hoster (domainFACTORY und 1und1 gehören dazu) stellen die Apache-Variable %{DOCUMENT_ROOT} nicht zur Verfügung. Das führt zu einem unvollständigen Datei-Pfad. In solchen Fällen bitte den Document-Pfad manuell (statt Variable) voranstellen, siehe Anleitung DOCUMENT_ROOT in .htaccess durch Serverpfad ersetzen.
*Broken Link*: http://cup.wpcoder.de/htaccess-document-root/

Link redirects to Sergej's front page on Github: https://sergejmueller.github.io/

**Comment by Zodiac1978** [comment]
Thank you very much. I found a post about this problem and replaced the link.
