### ISSUE TITLE
Gives 500 Internal Server Error when we add hdd cache htaccess code

### ISSUE THREAD

**Issue by vintagepornbay** [pluginkollektiv/cachify#72]
Hi this plugin's hdd cache htaccess code gives 500 internal server error when we add it into our htaccess, why?

**Comment by Zodiac1978** [comment]
Issues are for reporting bugs or feature request but not for support.

If you think there is a bug, please post the exact code you are using and your server specs, because without these info we can't reproduce and debug this problem.

**Comment by vintagepornbay** [comment]
This is code i added into htaccess both using ftp and bps security plugin:
`# BEGINN CACHIFY
<IfModule mod_rewrite.c>
    # ENGINE ON
    RewriteEngine On

    # GZIP FILE
    <IfModule mod_mime.c>
        RewriteCond %{REQUEST_URI} /$
        RewriteCond %{REQUEST_URI} !^/(wp-admin|wp-content/cache)/.*
        RewriteCond %{REQUEST_METHOD} !=POST
        RewriteCond %{QUERY_STRING} =""
        RewriteCond %{HTTP_COOKIE} !(wp-postpass|wordpress_logged_in|comment_author)_
        RewriteCond %{HTTP:Accept-Encoding} gzip
        RewriteCond %{DOCUMENT_ROOT}/path to/wp-content/cache/cachify/%{HTTP_HOST}%{REQUEST_URI}index.html.gz -f
        RewriteRule ^(.*) /path to/wp-content/cache/cachify/%{HTTP_HOST}%{REQUEST_URI}index.html.gz [L]

        AddType text/html .gz
        AddEncoding gzip .gz
    </IfModule>

    # HTML FILE
    RewriteCond %{REQUEST_URI} /$
    RewriteCond %{REQUEST_URI} !^/(wp-admin|wp-content/cache)/.*
    RewriteCond %{REQUEST_METHOD} !=POST
    RewriteCond %{QUERY_STRING} =""
    RewriteCond %{HTTP_COOKIE} !(wp-postpass|wordpress_logged_in|comment_author)_
    RewriteCond %{DOCUMENT_ROOT}/path to/wp-content/cache/cachify/%{HTTP_HOST}%{REQUEST_URI}index.html -f
    RewriteRule ^(.*) /path to/wp-content/cache/cachify/%{HTTP_HOST}%{REQUEST_URI}index.html [L]
</IfModule>
# END CACHIFY`

That htaccess code gives 500 internal server error.
However without adding that code cachify still runs and generates hdd cache zip files. 

The server is from Godaddy and unlimited shared hosting.

**Comment by Zodiac1978** [comment]
As I said, this is not for support. Please check your error logs (if possible) and contact GoDaddy support as I am not familiar with the limitations on those shared hosting environments.

If they do not support `mod_rewrite` the `ifmodule`check should prevent any Internal Server Errors. Maybe some of the variables are not supported from your hoster.

**Comment by Zodiac1978** [comment]
Maybe this support page from GoDaddy can help:
https://de.godaddy.com/help/what-do-i-do-when-i-receive-an-internal-server-error-1655

**Comment by wplike** [comment]
Hello vintage,

you get this error 500 because of this :  /path to/

The 2 rules you have to modify :  RewriteRule ^(.*) /path to/wp-content/cache/etc...
To these one :  RewriteRule ^(.*) /wp-content/cache/etc...

Regards.
