### ISSUE TITLE
nginx memcached "connection refused" on first page load

### ISSUE THREAD

**Issue by summerjob** [pluginkollektiv/cachify#89]
I get this error each time a browser loads a chached page for the first time.
The second load from cache generates no error

`[error] 22914#22914: *78 connect() failed (111: Connection refused) while connecting to upstream, client: 49.123.123.123, server: example.com, request: "GET /my-blog-post/ HTTP/2.0", upstream: "memcached://[::1]:11211", host: "example.com", referrer: "https://example.com/"`

Or could this be caused by my ip-tables firewall? If so what rule do I have to add?

**Comment by krafit** [comment]
@bueltge any idea on this issue?

**Comment by timse201** [comment]
> upstream: "memcached://[::1]:11211",

its given in description inside the plugin:
If you have errors please try to change memcached_pass localhost:11211; to memcached_pass 127.0.0.1:11211;
This forces IPv4 because some servers that allow IPv4 and IPv6 are configured to bind memcached to IPv4 only.

**Comment by Zodiac1978** [comment]
@summerjob You never reported back here. Does this solved your issue? Can we close it?

**Comment by Zodiac1978** [comment]
Closing due to missing reporter feedback. Please re-open if still valid.
