### ISSUE TITLE
Clean up the use of @ operator

### ISSUE THREAD

**Issue by chesio** [pluginkollektiv/cachify#99]
Inspired by discussion in #98. Here's a list of current uses of `@` operator in the plugin:
- [x] [inc/cachify.class.php:1596-1598](https://github.com/pluginkollektiv/cachify/blob/master/inc/cachify.class.php#L1596-1598)
- [ ] [inc/class-cachify-apc.php:103](https://github.com/pluginkollektiv/cachify/blob/2abed98e1029729ab55a1d5e8b5723176213070c/inc/class-cachify-apc.php#L103)
- [x] [inc/class-cachify-hdd.php:115](https://github.com/pluginkollektiv/cachify/blob/2abed98e1029729ab55a1d5e8b5723176213070c/inc/class-cachify-hdd.php#L115)
- [ ] [inc/class-cachify-hdd.php:188](https://github.com/pluginkollektiv/cachify/blob/2abed98e1029729ab55a1d5e8b5723176213070c/inc/class-cachify-hdd.php#L188)
- [x] [inc/class-cachify-hdd.php:195](https://github.com/pluginkollektiv/cachify/blob/2abed98e1029729ab55a1d5e8b5723176213070c/inc/class-cachify-hdd.php#L195)
- [ ] [inc/class-cachify-hdd.php:200](https://github.com/pluginkollektiv/cachify/blob/2abed98e1029729ab55a1d5e8b5723176213070c/inc/class-cachify-hdd.php#L200)
- [x] [inc/class-cachify-hdd.php:203](https://github.com/pluginkollektiv/cachify/blob/2abed98e1029729ab55a1d5e8b5723176213070c/inc/class-cachify-hdd.php#L203)
- [ ] [inc/class-cachify-hdd.php:254](https://github.com/pluginkollektiv/cachify/blob/2abed98e1029729ab55a1d5e8b5723176213070c/inc/class-cachify-hdd.php#L254)
- [x] [inc/class-cachify-memcached.php:140](https://github.com/pluginkollektiv/cachify/blob/2abed98e1029729ab55a1d5e8b5723176213070c/inc/class-cachify-memcached.php#L140)

Let's try to reduce this list to necessary minimum :-)

**Comment by angcl** [comment]
Perhaps this issue could be closed now because #256 was merged.

**Comment by stklcode** [comment]
The _master_ references in the first comment pointed to inexisting files. I've just updated them by comparing the code from 05/2017 to the current _develop_ state with fixed commit references.

4 usages are left and 2 new. One of them has custom error handling. Is there any scenario in which a warning from the other calls is really superfluous?

https://github.com/pluginkollektiv/cachify/blob/78914d855f2f74371e02e071e26c5249be4b4aa8/inc/class-cachify-apc.php#L99

This is plain suppression without any custom handling. If the call fails, flusing did not work and the user probably won't notice.

https://github.com/pluginkollektiv/cachify/blob/78914d855f2f74371e02e071e26c5249be4b4aa8/inc/class-cachify-hdd.php#L208-L209

Error handling is done in the next line using `trigger_error`.

https://github.com/pluginkollektiv/cachify/blob/78914d855f2f74371e02e071e26c5249be4b4aa8/inc/class-cachify-hdd.php#L220-L221

If the `stat()`  call fails here and the result is `false`, a warning is generated in the very next line with a warning like "Trying to access array offset on value of type bool".
I would prefer the original warning "stat failed for [filename]" here.

https://github.com/pluginkollektiv/cachify/blob/78914d855f2f74371e02e071e26c5249be4b4aa8/inc/class-cachify-hdd.php#L223

Hm ...

https://github.com/pluginkollektiv/cachify/blob/78914d855f2f74371e02e071e26c5249be4b4aa8/inc/class-cachify-hdd.php#L259-L262

If this fails, we leave some directories on the filesystem. It should not occur, if `_user_can_delete` is implemented correctly.

https://github.com/pluginkollektiv/cachify/blob/78914d855f2f74371e02e071e26c5249be4b4aa8/inc/class-cachify-redis.php#L119

This one's new.

**Comment by stklcode** [comment]
Closing this one for now. There a few @'s left, but we are aware of it and should not simply remove these. Would still be nice to get rid of even more, but using e.g. `WP_Filesystem` calls instead of direct access (which is something we should have a look into anyway) would also just shift the @'s down another method call outside our scope, so no real improvement.
